frame_id     : map
base_frame_id: base_footprint

resolution: 0.05
height_map: true

sensor_model:
  max_range: -1
  hit      : 0.7
  miss     : 0.4
  min      : 0.12
  max      : 0.97

# latch is recommended to be false while building a map
latch: false

filter_ground: false

ground_filter:
  distance      : 0.04
  angle         : 0.15
  plane_distance: 0.07

pointcloud_min_z: -.Inf
pointcloud_max_z:  .inf

occupancy_min_z: -.Inf
occupancy_max_z:  .inf
