# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  global_frame    : map
  robot_base_frame: base_footprint

  update_frequency : 10.0
  publish_frequency: 1.0

  transform_tolerance: 0.2

  track_unknown_space: true
  unknown_cost_value : 255

  robot_radius: 0.275

  # attention, the order and combination method matters
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_vo_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  static_layer:
    enabled  : true
    map_topic: vo_map

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 6.0
      obstacle_range: 5.0
      min_obstacle_height: -0.1
      max_obstacle_height: 0.4

  obstacle_vo_layer:
    enabled: true
    observation_sources: vo_cloud
    combination_method: 1

    vo_cloud:
      sensor_frame: base_link
      data_type: PointCloud
      topic: vo_cloud
      expected_update_rate: 12.0
      observation_persistence: 0.0
      marking: true
      clearing: false
      raytrace_range: 1.0
      obstacle_range: 20.0
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0


  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 25.0
